spring:
  application:
    name: GestioneFatture
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: francescod!
    url: jdbc:mysql://212.131.189.19:30016/francescod
    username: francescod
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true